example/skel/src/lib.rs, src/php/args.rs, src/php/enums.rs, src/php/types.rs, src/php/zval.rs
- A long can now be turned into a double, which can be turned into a string.
- Updated example
=> Added argument overloading

Cargo.toml, build.rs
Ensure that the user is compiling with a supported version
of PHP.
Closes #10
=> Check PHP API version in build script

example/skel/src/lib.rs, example/skel/test.php, src/php/types/array.rs
We shouldn't really be returning Zval objects, rather references to Zval
objects. There is currently a memory leak with arrays that need to be
resolved.
=> Refactored ZendHashTable conversions

src/php/types/zval.rs
- Replaced manual TryFrom implementations on Zval with a generic macro. Using this implemented on most types.
- `Zval::set_long`, `Zval::set_double` and `Zval::set_bool` now accept any type which implements `Into<T>` where T is the type that the function originally took.
=> Replaced manual TryFrom implementations with macro

src/errors.rs, src/lib.rs, src/php/args.rs, src/php/enums.rs, src/php/types/array.rs, src/php/types/zval.rs
- Provides a better debugging experience.
- Added `Zval::get_type() -> Result<DataType>`.
=> Replace unit errors with error enum

example/skel/src/lib.rs, example/skel/test.php, src/macros.rs, src/php/args.rs, src/php/function.rs, src/php/module.rs, src/php/types/array.rs, src/php/types/object.rs, src/php/types/string.rs, src/php/types/zval.rs
Most types did not have Debug and Clone implementations, as the Zend API has many unions which cannot implement Debug. Added `#[derive(Debug)]` implementations where possible and added expanded impls where not possible to derive.
Added `throw!()` to throw and return. Translates into the following:
```rs
throw(ClassEntry::exception(), "reason");
return;
```
=> Added Debug and Clone implementations

Cargo.toml
Remove default-features=false from bindgen build dependency to fix failing builds with crates that have multiple different dependencies that both depend on bindgen.
See failed pipeline here for the error in question - https://gitlab.com/willbrowning/anonaddy-sequoia/-/jobs/1238041327
I believe this may be related to this issue - https://github.com/rust-lang/rust-bindgen/issues/2030
=> Remove default-features=false from bindgen

example/skel/src/lib.rs, example/skel/test.php, src/php/args.rs, src/php/class.rs, src/php/types/array.rs, src/php/types/object.rs, src/php/types/string.rs, src/php/types/zval.rs
Objects are now returned as references (mutable where appropriate), allowing them to be interacted with. Implemented `Debug` and other common traits.
=> Better interactions with objects

example/skel/src/lib.rs, ext-php-rs-derive/src/lib.rs, src/errors.rs, src/functions.rs, src/lib.rs, src/macros.rs, src/php/args.rs, src/php/class.rs, src/php/constants.rs, src/php/exceptions.rs, src/php/function.rs, src/php/module.rs, src/php/types/array.rs, src/php/types/object.rs, src/php/types/string.rs, src/php/types/zval.rs
Some functions will now return `Result`s where previously things were unwrapped. Most things should stay the same, but you may have to insert some `.unwrap()` or `.expect()` calls in (or match if you really want to!)
Functions that have changed:
- `.build()` returns `Result` on `FunctionBuilder`, `ClassBuilder` and `ModuleBuilder`.
- `.property()` and `.constant()` return `Result` on `ClassBuilder`.
- `.register_constant()` returns `Result`.
- `.try_call()` on callables now return `Result` rather than `Option`.
- `throw()` and `throw_with_code()` now returns `Result`.
- `new()` and `new_interned()` on `ZendString` now returns a `Result`.
For `ZendHashTable`:
- `insert()`, `insert_at_index()` now returns a `Result<HashTableInsertResult>`, where `Err` failed, 
`Ok(Ok)` inserts successfully …
=> Remove uses of `unwrap`, improve library safety

example/skel/src/allocator.rs, example/skel/src/lib.rs, example/skel/test.php, ext-php-rs-derive/src/extern_.rs, ext-php-rs-derive/src/lib.rs, src/lib.rs, src/macros.rs, src/php/types/binary.rs, src/php/types/callable.rs, src/php/types/zval.rs
Adds ability to import PHP functions into Rust.
=> Added `#[php_extern]` macro

Cargo.toml, build.rs, example/skel/Cargo.toml, example/skel/src/allocator.rs, example/skel/src/lib.rs, src/php/alloc.rs, src/php/mod.rs, src/php/types/object.rs
The object memory is automatically deallocated, however, anything that
has been allocated on the heap (strings, vectors etc.) must be
deallocated while we are freeing the object.
=> Drop object contents rather than deallocating whole object

Cargo.toml, build.rs, src/php/alloc.rs, src/php/module.rs
e.g. PHP debug or ZTS mode are no longer features, but just simply
configuration flags.
=> Use configuration tags instead of features for flags

.github/workflows/build.yml, .github/workflows/docs.yml, build.rs
Tidied up build script as well, layout tests are no longer generated
unless `EXT_PHP_RS_TEST` env variable is set. Much quicker build times
and smaller output size.
=> Allowlist types generated by bindgen

example/skel/src/lib.rs, src/php/args.rs, src/php/types/array.rs, src/php/types/binary.rs, src/php/types/object.rs, src/php/types/zval.rs
Allows generic implementations of the `FromZval` trait.
You can now take `&T` as a parameter, where `T: RegisteredClass`.
=> Add `try_from` into `FromZval` trait

build.rs, docsrs_bindings.rs, example/skel/src/lib.rs, example/skel/test.php, ext-php-rs-derive/src/class.rs, src/php/args.rs, src/php/class.rs, src/php/enums.rs, src/php/function.rs, src/php/types/closure.rs, src/php/types/mod.rs, src/php/types/object.rs, src/php/types/zval.rs
Previously, when returning or taking a class object the type would be `object`, rather than the actual class name.
=> Pass class object type to PHP when taking object parameter

src/php/execution_data.rs, src/php/types/object.rs
When there was padding between `obj` and `std`, this would be ignored by the library, leading to errors.
=> Fix alignment of class objects

ext-php-rs-derive/Cargo.toml, ext-php-rs-derive/src/impl_.rs, ext-php-rs-derive/src/lib.rs, ext-php-rs-derive/src/method.rs
I'd be surprised if the patch will be taken in this form, but I'm willing to put the effort in to getting this in should there be interest.
Rust loves using snake_case for functions, but to comply with PSR-1, methods should be in camelCase. This patch tries to change the case of methods generated through the `php_impl` macro.
As for precedence for changing the case of identifiers via macros, both juniper and async-graphql do this.
=> Naively change the case of method identifiers to comply with PSR-1

build.rs, example/skel/src/lib.rs, example/skel/test.php, src/php/enums.rs, src/php/globals.rs, src/php/types/array.rs, src/php/types/binary.rs, src/php/types/mod.rs, src/php/types/object.rs, src/php/types/rc.rs, src/php/types/zval.rs
- `ZendHashTable` has been split into `&HashTable` and `OwnedHashTable`. `&HashTable` is to `OwnedHashTable` as `&str` is to `String`.
- The `Drop` implementation on `Zval` will properly drop the contents of the zval.
=> Refactor `ZendHashTable` and `Zval`

Cargo.toml, build.rs, example/skel/src/lib.rs, example/skel/test.php, src/php/class.rs, src/php/types/array.rs, src/php/types/object.rs, src/php/types/string.rs, src/php/types/zval.rs
Zend strings now come in two forms - the borrowed `&ZendStr` and the owned `ZendString`, which can be compared to `&str` and `String`.
=> Refactor Zend strings

CHANGELOG.md, Cargo.toml, docsrs_bindings.rs, ext-php-rs-derive/Cargo.toml, guide/src/macros/impl.md
- Bumped versions
- Updated changelog
- Updated docs.rs bindings
- Updated documentation about rename methods
=> Prepared for v0.5.0 release

CHANGELOG.md, ext-php-rs-derive/src/function.rs, ext-php-rs-derive/src/method.rs, guide/src/macros/structs.md, src/errors.rs, src/lib.rs, src/php/exceptions.rs, src/php/types/object.rs, src/php/types/zval.rs
All class entries are effectively static (module start to module end) so
it's just a hassle carrying the lifetime everywhere.
Closes #68
=> Remove lifetime from `PhpException`

build.rs, src/php/globals.rs, src/php/types/object.rs, src/php/types/zval.rs
Small PR that brings part of my work getting eval/compile support built.
Adds some basic support for capturing PHP exceptions, function calling, and convenience methods around converting from Zval to Rust types.
Which that groundwork in place, add a PHP equivalent implementation for Display.
=> Add Display impl for ZendObject

CHANGELOG.md, ext-php-rs-derive/src/class.rs, ext-php-rs-derive/src/function.rs, ext-php-rs-derive/src/impl_.rs, ext-php-rs-derive/src/method.rs, ext-php-rs-derive/src/module.rs, guide/src/macros/classes.md, guide/src/macros/impl.md, src/lib.rs, src/php/class.rs, src/php/execution_data.rs, src/php/types/closure.rs, src/php/types/object.rs, src/php/types/zval.rs
Constructor methods can now be specified. They are required if
you want to construct the class from PHP. This replaces the `Default`
implementation requirement on class objects.
Constructors can return `Self` or `Result<Self, E>` where `E: Into<PhpException>`.
=> Add class constructors

.github/workflows/build.yml, Cargo.toml, build.rs, example/skel/Cargo.toml, ext-php-rs-derive/src/zval.rs, src/php/boxed.rs, src/php/class.rs, src/php/execution_data.rs, src/php/mod.rs, src/php/pack.rs, src/php/types/array.rs, src/php/types/object.rs, src/php/types/string.rs, src/php/types/zval.rs
Currently types which cannot be owned directly are owned through wrapper types,  such as `ZendString -> ZendStr`, `OwnedHashTable -> HashTable`, `ClassObject -> ZendObject`, since they are allocated using the Zend memory manager and cannot be stored in a box.
This PR introduces a new type `ZBox<T>` and a new trait `ZBoxable`. A type allocated using the Zend memory manager will implement `ZBoxable`, and can then be stored inside a `ZBox<T>`.
There are no 'safe' constructor methods on `ZBox`. These are to be implemented on the boxed types. For example, `ZendStr` has a function `from_c_str` which returns a `ZBox<ZendStr>`.
=> Add `ZBox<T>` to replace owned variants

src/binary.rs, src/builders/function.rs
Seems like `c_char` is different on AArch64 Linux (even though it's the same as x86 on AArch64 macOS).
=> Fix builds on aarch64 Linux

src/class.rs
This wasn't the case because of `PhantomData<T>` inside the metadata.
Replacing this with `PhantomData<AtomicPtr<T>>` ensures that the
metadata will always be `Send + Sync`.
=> Make `ClassMetadata: Send + Sync`

Cargo.toml, src/class.rs, src/props.rs, src/zend/handlers.rs
This adds `once_cell` as a dependency, however, it is used for both
handlers and properties. Better to be 'safe' than sorry ;)
=> Create properties hashmap once instead of on each call

src/builders/module.rs
Request specific builder methods were assigning to the wrong fields,
overwriting the MINIT/MSHUTDOWN functions, instead of RINIT/RSHUTDOWN.
=> Fix request_(startup|shutdown)_function in ModuleBuilder

crates/macros/src/class.rs, crates/macros/src/startup_function.rs
Allows raw access to the `ClassBuilder` object (e.g. for adding constants).
=> Add ability to pass modifier function for classes

src/types/string.rs
It is currently breaking the build with +nightly.
=> Fix clippy warning, unused lifetime parameter

build.rs, guide/src/SUMMARY.md, guide/src/types/binary_slice.md, guide/src/types/index.md, src/binary_slice.rs, src/boxed.rs, src/lib.rs, src/props.rs, src/types/callable.rs, src/types/class_object.rs, src/types/zval.rs, src/zend/ex.rs, src/zend/handlers.rs
For optimized applications where we need to read binary data (for example calculating checksums), I propose to add a new type `BinarySlice<T>` along the current `Binary<T>` in order to avoid allocation/copying. This type can only be used as a parameter and not return value on the Rust side, since modifying the binary string is not allowed. For our usage, this improves the running time by about -20%.
Up for discussion: should we keep this in `binary_slice` or move it to `binary`?
Please let me know if there is a need for additional documentation somewhere.
=> Support for BinarySlice to avoid allocation

guide/src/introduction.md, guide/src/macros/impl.md
Hi, 
I've fixed some typos I discovered.
Thank you for building this amazing project.
=> Fixed some typos

CHANGELOG.md, allowed_bindings.rs, crates/macros/src/module.rs, guide/src/types/closure.md, src/boxed.rs, src/builders/class.rs, src/builders/function.rs, src/class.rs, src/convert.rs, src/describe/stub.rs, src/exception.rs, src/lib.rs, src/macros.rs, src/types/array.rs, src/types/callable.rs, src/types/class_object.rs, src/zend/ex.rs, windows_build.rs
Fixes typos in various files, mostly comments. No functional changes.
=> Fix a few typos

crates/macros/src/module.rs
Clippy linting had more errors:
error: iterating on a map's values
Error:   --> crates/macros/src/module.rs:56:36
|
56 |       let registered_classes_impls = state
|  ____________________________________^
57 | |         .classes
58 | |         .iter()
59 | |         .map(|(_, class)| generate_registered_class_impl(class))
| |________________________________________________________________^
|
= note: `-D clippy::iter-kv-map` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_kv_map
help: try
|
56 ~     let registered_classes_impls = state
57 +         .classes.values().map(|class| generate_registered_class_impl(class))
|
error: iterating on a map's values
Error:    --> crates/macros/src/module.rs:366:23
|
366 | …
=> fix more causes of clippy warnings

crates/cli/src/lib.rs
This should fix the errors from the build at
<https://github.com/davidcole1340/ext-php-rs/actions/runs/3145521955/jobs/5112909446>:
Compiling clap v4.0.0
error: Unknown `#[clap(long)]` attribute (`#[arg(long)] exists)
--> crates/cli/src/lib.rs:92:12
|
92 |     #[clap(long)]
|            ^^^^
error: Unknown `#[clap(long)]` attribute (`#[arg(long)] exists)
--> crates/cli/src/lib.rs:115:12
|
115 |     #[clap(long)]
|            ^^^^
error: Unknown `#[clap(short)]` attribute (`#[arg(short)] exists)
--> crates/cli/src/lib.rs:134:12
|
134 |     #[clap(short, long)]
|            ^^^^^
error: could not compile `cargo-php` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
These errors were probably caused by the release …
=> attempt to fix errors related to `clap`

.github/workflows/build.yml
~**Note:** This is _still a draft_, because it should only be merged after #158 was approved and merged.~
---
Sparked by the comments about nightly clippy breaking the build too often (see <https://github.com/davidcole1340/ext-php-rs/pull/151#issuecomment-1261151479>), this change will limit clippy to builds with a stable Rust version only.
=> ci: run clippy only on stable Rust channel

.github/workflows/build.yml, .github/workflows/docs.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`
> - Bumped various npm package versions
>
> ## v3.0.0
>
> - Update to node 16
As far as I can tell this should all be backwards compatible, so I do not expect any breakage.
=> update actions/checkout in GitHub Actions workflows to v3

crates/macros/src/function.rs
This is much the same as `php_class(name="ABC")`
=> Add ability to set function name on php_function macro

src/describe/stub.rs
When stubs are generated, the type annotations don't use a loading `\`, which means they are interpreted as relative to the current namespace. That's wrong, as all types are relative to the root namespace.
=> Specify classes as fully-qualified names in stubs

crates/macros/src/class.rs, crates/macros/src/startup_function.rs
This allows passing flags as part of `#[php_class(flags=Interface]` etc, which allows one to mark a class as being an interface.
When a class is an interface, it also shouldn't get a constructor created for it.
=> Support marking classes as interfaces

crates/macros/src/impl_.rs, crates/macros/src/method.rs
For classes that are registered with `#[php_impl]` this allows functions to be marked as abstract.
=> Support marking methods as abstract

README.md
Hey There 👋 
We at Appwrite recently created an extension using this library to fix an issue we had with the standard C-based php-scrypt by rewriting it in rust. Thanks to this library being so easy to use, we could get a working version in less than a day! 
We would love it if you could add it as an example project in this repository to give more examples of how to use this library.
Thank you for reviewing this pull request,
Bradley Schofield
=> Add php-scrypt as a example project

crates/cli/src/lib.rs
Addresses https://github.com/davidcole1340/ext-php-rs/issues/134
Also prevents the extension line from being added twice on subsequent calls.
=> Fix ini file duplication and truncation when using `cargo-php` command

crates/cli/README.md, crates/cli/src/lib.rs, guide/src/cargo-php.md
Makes this tool usable in automated builds such as Docker containers.
Addresses https://github.com/davidcole1340/ext-php-rs/issues/133
=> Allow passing `--yes` parameter to bypass prompts

CHANGELOG.md
Updates the changelog so that the changes for the newer releases are included, too.
=> Update changelog for latest versions

guide/src/macros/classes.md
I've managed to implement an interface as described in #163 and want to provide an example on how to do it. This example is based on the work in #164.
Closes #163
=> Add example that shows how to implement an interface

crates/cli/Cargo.toml
It removes some error about not found `arg` macro
=> chore(cli): Bump Clap for CLI tool

src/zend/class.rs
=> fixes inifinte loop in ClassEntry::instance_of()

src/binary_slice.rs, src/types/zval.rs
returned slice should have the same lifetime as the zend string (which will have the same lifetime as the Zval).
=> fix binary slice lifetimes

.github/workflows/build.yml, .github/workflows/docs.yml, src/types/zval.rs
The latest runs were broken for some reason so I fixed it.
Here's a summary of what this PR does:
* upgrades LLVM to v14
* migrates from the unmaintained `action-rs/*` actions to [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain), using [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache/) as a cache layer.
* adds a cache layer for LLVM build
* adds a weekly cron schedule for all workflows
* fixes an issue in the docblocks
=> fixes CI workflow configuration

src/types/object.rs
The `get_id` method is strictly equivalent to calling `spl_object_id()` with the object as parameter.
The `get_hash` method is strictly equivalent to calling `spl_object_hash()` with the object as parameter.
=> Add get_id() and hash() methods on ZendObject

src/types/object.rs
Summary:
* adds `ZendObject::get_class_entry()` to retrieve the class entry of an object without casting pointers
* adds `ZendObject::instance_of()` to allow more idiomatic instanceof checks.
* adds a mention that `ZendObject::is_instance::<T>()` does not check the parent classes or interfaces. This bit me when I tried to check if `my_object.is_instance::<MyInterface>()` and it didn't work.
=> Add instance_of() and get_class_entry() methods on ZendObject

Cargo.toml, build.rs, unix_build.rs, windows_build.rs
I currently have over 18 PHP installations locally, having to swipe between them for different projects is kinda annoying, so here's my solution for the problem :)
[`php-discovery`](https://github.com/azjezz/php-discovery) will attempt to find all PHP builds in the system, even if not listed in `PATH`, and create a struct representing each build, containing all information necessary for ext-php-rs.
note: ext-php-rs will still have to do the work to get `includes` on windows, while i can certainly add it as a feature in [`php-discovery`](https://github.com/azjezz/php-discovery), i feel that it doesn't belong, and that it should do only 1 job, which is discover available PHP builds.
=> chore: use php-discovery to find matching PHP build

.gitignore, allowed_bindings.rs, src/builders/class.rs, src/error.rs, src/ffi.rs, src/types/object.rs, src/types/string.rs, src/types/zval.rs, src/wrapper.c, src/wrapper.h, src/zend/class.rs, src/zend/handlers.rs
Closes #200
In PHP zend_strings are binary strings with no encoding information. They can contain any byte at any position.
The current implementation use `CString` to transfer zend_strings between Rust and PHP, which prevents zend_strings containing null-bytes to roundtrip through the ffi layer. Moreover, `ZendStr::new()` accepts only a `&str`, which is incorrect since a zend_string is not required to be valid UTF8.
When reading the PHP source code, it is apparent that  most functions marked with `ZEND_API` that accept a `const *char` are convenience wrappers that convert the `const *char` to a zend_string and delegate to another function. For example [zend_throw_exception()](https://github.com/php/php-src/blob/eb83e0206c9b9261d786943bf2c5ad61dca287e2/Zend/zend_exceptions.c#L823) takes a …
=> feat: allows ZendStr to contain null bytes

allowed_bindings.rs, docsrs_bindings.rs, src/types/zval.rs
I was missing the ability to compare two zvals with PHP's `===` operator. 
To allow for it, I exposed the `zend_is_identical` function that the Zend engine maps to the `===` token.
=> Add is_identical for zvals

src/zend/globals.rs
THis is useful if you want to insert global variables or the like into the the global executor.
=> Mate GlobalExecutor::get_mut() public

crates/macros/src/startup_function.rs
Currently the startup function macro will wrap the function body in an `intneral()` function, which has no params. This makes it impossible to acess the `ty` and `module_number` values that PHP passes to the startup function.
=> Pass args to startup function

src/flags.rs
IS_PTR (`13`) must be checked before any lower values, else it is never detected.
=> Fix Zval IS_PTR type detection

build.rs
When loaded via Cargo, there's no Cargo.lock directly in this crate, so the lack of file existence causes unnecessary rebuilds every time.
Fixes #220.
=> Stop watching Cargo.lock for changes

README.md
This pull request fixes the display of two badges in the readme file.
See <https://github.com/badges/shields/issues/8671> for more information about the breaking change in the URL scheme.
=> Fix URL of shields.io badges in README.md

Cargo.toml, src/flags.rs, src/types/zval.rs
- bitflags to v2 
- Sync Cargo config
=> chore: deps upgrade

src/zend/globals.rs
ExecutorGlobals::constants() will return a hash map of the available constants.
=> Add helper to get global constants

src/builders/module.rs, src/convert.rs
When using call_user_func!() / Callable::try_call() it's currently not possible to use Zvals in the arguments which is unexepected. The simplest way is to add the trait to Zval's too.
=> Implement IntoZvalDyn for Zval

crates/macros/src/function.rs, guide/src/types/bool.md
Currently it's not possible for a function to accept args by reference. This PR adds early support for doing so, by transforming any function args that are `&mut T` into args that are passed by reference. E.g.:
```
#[php_function]
fn my_function( arg: &mut Zval ) {
arg.reference_mut().map( |zval| zval.set_bool(true) );
}
```
=> Support function args being passed by reference

src/embed/embed.c, src/embed/embed.h, src/embed/ffi.rs, src/embed/mod.rs
This correctly shutdown php runtime when there is a panic (like a failed test) inside the embed sapi, otherwise a panic would cause a segfault (since php runtime is not correctly shutdown)
=> feat(embed): correctly handle panic inside embed

allowed_bindings.rs, build.rs, docsrs_bindings.rs, src/embed/embed.c, src/embed/ffi.rs, src/embed/mod.rs, src/ffi.rs, src/wrapper.c, src/wrapper.h, src/zend/mod.rs, src/zend/try_catch.rs
This should allow extension to wrap their code under the try catch mechanism of PHP
=> feat(zend): add helper for try catch and bailout in PHP

src/builders/class.rs, src/types/class_object.rs, src/zend/handlers.rs
See #138
The `ce` should be taken from the `create_object`. From that point on, everything else can carry on just about normal. the only thing that needs to change is the sanity check to make sure the `ClassEntry` for the object passed to the object handlers is a child as well as the direct class.
=> Forward ClassEntry in create_object

.github/workflows/build.yml, .github/workflows/docs.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20
=> Update actions/checkout in GitHub Actions workflows to v4

src/zend/globals.rs
Just a test for now. Goal is fixing CI. If merged with these changes:
BREAKING CHANGE: If you used `http_request_vars()` before it will now panic until a proper implementation is found.
Refs: #331
=> fix(globals)!: disabled `$_REQUEST` super global function

crates/cli/.gitignore, crates/macros/.gitignore
When I ran `git status` I got this message:
```
warning: unable to access 'crates/macros/.gitignore': Too many levels of symbolic links
warning: unable to access 'crates/cli/.gitignore': Too many levels of symbolic links
```
Since git 2.23 `.gitignore` that is a symbolic link is ignored. I made them explicit now (though I'm not sure they're even needed)
=> Don't use symbolic links for git.

windows_build.rs
Follow up to https://github.com/davidcole1340/ext-php-rs/pull/338
Windows bulds should check the releases page, and the archive, as it's not clear when they'll be moved by Microsoft.
=> Windows build should try archives

src/types/array.rs, src/types/callable.rs, src/types/iterable.rs, src/types/object.rs, src/types/zval.rs
=> refactor(clippy): fix new clippy errors

README.md, windows_build.rs
This change enables the extension to be compiled correctly in debug mode.
The issue was that, in the default case, the builder attempted to use files from the PHP DEV PACK, which lacks debug symbols. This resulted in a linker error, as it couldn't find the emalloc functions (these have different signatures in DEBUG builds).
Solution:
* Add an environment variable `PHP_LIB`.
* Check if we are compiling in debug mode. If so, require this variable to be set. Otherwise, proceed as before.
* `PHP_LIB` must point to a built `PHP` instance. The library name is chosen as `php8ts_debug.lib`.
P.S. I tried to find a place in the documentation to add this, but I can't figure out where it should go. If you can provide details, I would certainly include it.
=> Windows - add a DEBUG build with debugging symbols

README.md, build.rs
=> chore(php): add deprecation warning for php 8.0

src/types/array.rs, tests/src/integration/array.php, tests/src/integration/array.rs
=> fix(array): fix null dereference in iterator

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/release-plz.yml, .release-plz.toml, README.md, crates/cli/Cargo.toml
=> ci(release): add release bot

build.rs, src/builders/class.rs, src/flags.rs
=> chore(cfg): change php81 cfg to 8.1+

src/types/array.rs, tests/src/integration/iterator.php, tests/src/integration/iterator.rs, tests/src/lib.rs
=> fix(array): fix double ended iterator implementation

README.md, crates/cli/README.md, guide/src/getting-started/cargo-php.md
=> docs(cargo-php): add locked option to install guide

src/embed/mod.rs, tests/module.rs
`zend_register_module_ex` change its signature in php 8.4
=> chore(test): fix embed test on php 8.4

crates/macros/Cargo.toml, crates/macros/src/class.rs, crates/macros/src/function.rs, crates/macros/src/impl_.rs, crates/macros/src/lib.rs, crates/macros/src/module.rs, crates/macros/src/syn_ext.rs, crates/macros/src/zval.rs
Update syn to 2.0.100
Update darling to 0.20
=> chore(deps): update syn and darling

Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/cli/src/main.rs, src/constant.rs, src/describe/abi.rs, src/flags.rs, src/props.rs, src/types/array.rs, src/types/class_object.rs, src/types/iterable.rs, src/types/object.rs, src/types/zval.rs, src/zend/class.rs, src/zend/function.rs, src/zend/globals.rs, src/zend/ini_entry_def.rs, src/zend/linked_list.rs, src/zend/streams.rs
=> docs: enforce doc comments

Cargo.toml, src/zend/globals.rs
Since on zts each thread gets its own globals (at the exception of sapi_module), i updated the lock to be on local thread (instead of static) so we can update / get globals without getting lock by another thread when in ZTS
=> feat(zts): set lock per thread on zts build

crates/macros/src/impl_.rs
While impl interface registration, find error in proc macros php_impl
Is missing separator for quote
=> fix(macro): Add missing separator pipe in flags

.github/workflows/coverage.yml
=> ci(coverage): add coverage reporting

crates/macros/src/impl_.rs, tests/src/integration/class.php, tests/src/lib.rs
If try class static method from php it throws exception
```
Uncaught Error: Non-static method Test::staticTest()
```
Cause in proc_macros missing usage of MethodFlags::Static
```rust
#[php_class]
#[derive(Default)]
struct Test {}
#[php_impl]
impl Test {
#[php(constructor)]
fn new() -> Self {
Self {}
}
/// Declare as static method
fn static_test() -> String {
String::from("Hello")
}
}
```
```php
<?php
$t = new Test;
Test::staticTest(); // Get exception
```
In PR i change FnBuilder from single additional modifier with flag abstract to Vec<Modifier>, Myabe we should make uniq Vec, idk)
=> fix: Messing static flags in php_impl proc macro

crates/macros/src/impl_.rs, crates/macros/src/parsing.rs, tests/src/integration/magic_method.php, tests/src/integration/magic_method.rs, tests/src/lib.rs
I see how you @Xenira changed renaming, maybe change it to trait for common rename things and method?
=> refac: Make rename as Trait && separate to common rename, method_rename

crates/macros/src/lib.rs, crates/macros/src/module.rs, examples/hello_world.rs, guide/src/ini-settings.md, guide/src/migration-guides/v0.14.md
This unifies the behaviour of the `#[php_module]` macro and the other `#[php_*]` macros.
Refs: #423
=> refactor(macro): use `#[php]` attribute for startup function

build.rs
In windows, `where` command can return more than one line; this will cause the following error to be emitted when trying to invoke `php -i`:
```
The filename, directory name, or volume label syntax is incorrect. (os error 123)
```
This PR provides a fix for this error, taking only the first line of the output.
=> Take only the first line of which/where when searching for php executable

crates/macros/src/class.rs, crates/macros/src/lib.rs, guide/src/macros/classes.md, guide/src/migration-guides/v0.14.md, src/args.rs, src/builders/class.rs, src/builders/module.rs, src/class.rs, src/closure.rs, src/describe/abi.rs, src/describe/mod.rs, src/exception.rs, src/lib.rs, src/macros.rs, src/test/mod.rs, src/zend/ce.rs, tests/src/integration/class/class.php, tests/src/integration/class/mod.rs
BREAKING CHANGE: `extends` and `implements` attributes now require the `stub` property containing the class/interface name to be used in stubs.
Refs: #326
=> fix(class)!: generate correct stubs for extends and implements

crates/macros/src/function.rs, crates/macros/src/impl_.rs, tests/src/integration/defaults/defaults.php, tests/src/integration/defaults/mod.rs, tests/src/integration/mod.rs, tests/src/lib.rs
=> feat: argument defaults can be any valid expr

src/zend/handlers.rs, tests/src/integration/exception/exception.php, tests/src/integration/exception/mod.rs, tests/src/integration/mod.rs, tests/src/lib.rs
Fixes: #262
Partially derived from #313, this commit fixes access to object properties from Rust code. This is needed to correctly initialize exception objects.
=> fix: fixed object access in object write/read/has_property handlers

src/zend/globals.rs
I forked ext-php-rs [here](https://github.com/platformatic/ext-php-rs) for use in [php-node](https://github.com/platformatic/php-node) as I needed to make a bunch of changes. I want to backport as much of that as possible now so _ideally_ we don't need to maintain a fork at all. Just starting small here with this small bug I fixed.
When a header value contains a : character, which _is_ in fact valid according to the spec, it will fail in the current code as it will only include the text between the : separating the header name and the first : within the value. This fixes that by only splitting into two pieces.
=> Fix SapiHeader::value when value contains a : character

.dockerignore, .github/workflows/build.yml, .github/workflows/docsrs_bindings.yml, Dockerfile, README.md, allowed_bindings.rs, docsrs_bindings.rs, tools/update_bindings.sh
=> chore(bindings): add tooling to generate `docsrs_bindings.rs`

src/exception.rs
Running tests with `embed` feature but not `anyhow` features fails because this needs a cfg gate.
=> test: add missing cfg gate to anyhow exception test

Cargo.toml, guide/src/advanced/async_impl.md, guide/src/macros/classes.md, guide/src/types/functions.md, guide/src/types/iterable.md, guide/src/types/iterator.md, src/args.rs, src/zend/try_catch.rs
This disables automatic filesystem-based test inclusion, opting for manual inclusion so the guides, which rely on additional features, can skip running unless all their required features are enabled.
This also wraps a few tests with `Embed::run(...)` as they may crash if the PHP environment is not fully set up. I think that is specific to ZTS builds as some things are not set up until the PHP bootstrap functions get called.
=> test: improve test reliability and ease of use

crates/macros/src/class.rs, tests/src/integration/class/mod.rs
=> fix(macro): fix syntax error for `#[php_class]` with multiline doc comments

crates/macros/src/lib.rs
Before this usage of the old attributes was silently ignored causing confusion.
Refs: #464
=> fix(macro): return error when old macro attributes are used

crates/cli/src/lib.rs
https://github.com/davidcole1340/ext-php-rs/issues/452
=> feat(cargo-php): --features, --all-features, --no-default-features

src/builders/class.rs, src/lib.rs, src/types/array.rs, src/types/callable.rs, src/types/class_object.rs, src/types/iterable.rs, src/types/iterator.rs, src/types/object.rs, src/types/zval.rs, src/zend/class.rs, src/zend/function.rs, src/zend/globals.rs, src/zend/handlers.rs, src/zend/linked_list.rs, src/zend/streams.rs
- lifetime flowing from input to output with different syntax can be confusing
- mutable borrow from immutable input(s)
- chore(clippy): warning: implicit borrow as raw pointer
=> chore(clippy): flowing lifetimes warning and clippy::mut_from_ref

crates/cli/src/lib.rs
cargo-php fails to detect extension directory if there's a startup error in PHP.
```
Error: Failed to create extension directory at "\nWarning: PHP Startup: Invalid library (maybe not a PHP library) \'libuntitled5.dylib\' in Unknown on line 0\n/opt/homebrew/lib/php/pecl/20240924-zts"
Caused by:
No such file or directory (os error 2)
```
It's pretty annoying as it makes you go to php.ini and remove `extension=...` manually.
=> fix(cargo-php): get_ext_dir()/get_php_ini(): stdout noise tolerance

src/builders/function.rs
A quick fix for these errors:
```
PHP Deprecated:  Return type of EvenNumbersArray::offsetSet(mixed $offset, mixed $value): ?void should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
Deprecated: Return type of EvenNumbersArray::offsetSet(mixed $offset, mixed $value): ?void should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
PHP Deprecated:  Return type of EvenNumbersArray::offsetUnset(mixed $offset): ?void should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or …
```
=> fix(FunctionBuilder): return type '?void' is now just 'void'

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, .github/ISSUE_TEMPLATE/03_help.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> chore(github): add issue and pr templates

src/args.rs, tests/src/integration/defaults/defaults.php, tests/src/integration/defaults/mod.rs
Fixes #490
I see it is an ad-hoc fix to illustrate the issue. I hope that in the end we can arrive at a more fundamental fix + add some more test cases, as it looks quite fragile right now (all the string passing part)
:heart: Thank you
=> fix: support defaults for calls with named arguments

CHANGELOG.md, Cargo.toml, crates/macros/CHANGELOG.md, crates/macros/Cargo.toml
* `ext-php-rs-derive`: 0.11.0 -> 0.11.1
* `ext-php-rs`: 0.14.0 -> 0.14.1 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- Add missing parenthesis (by @Stranger6667) [[#486](https://github.com/davidcole1340/ext-php-rs/issues/486)]
</blockquote>
<blockquote>
- *(error)* Deprecate `E_USER_ERROR` in PHP 8.4 (by @Xenira) [[#476](https://github.com/davidcole1340/ext-php-rs/issues/476)] 
- Support defaults for calls with named arguments (by @Stranger6667) [[#490](https://github.com/davidcole1340/ext-php-rs/issues/490)] 
- Add missing parenthesis (by @Stranger6667) [[#486](https://github.com/davidcole1340/ext-php-rs/issues/486)]
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release

src/embed/embed.c, src/embed/embed.h, src/embed/ffi.rs, src/embed/sapi.rs, src/zend/globals.rs, src/zend/mod.rs, tests/sapi.rs
This enables a `SapiModule` to work in ZTS mode. I'm using `SapiModule` directly in my case rather than going through the `Embed` type. I missed this when submitting my other PR to expand `SapiBuilder`.
Not sure what making `Embed` ZTS-capable would look like as it would require constructing a single `SapiModule` and reusing it so the API might need to be different or it might need to do some internal `OnceCell` magic.
Not entirely sure how to test this in a way that's not rather complicated. The only observable difference I'm aware of is that without the change it _might_ randomly segfault eventually with enough parallel requests. Any ideas? 😅 
I'm already using this code in my fork, so I know it _works_, just writing a test that's not _gigantic_ would be a challenge. 🤔 
_Check the boxes …
=> feat: make Sapi work with ZTS builds

src/args.rs
Fixes: #501
Missing feature guard caused `cargo test` to fail linking.
_Check the boxes that apply (put an `x` in the brackets, like `[x]`). You can also check boxes after the PR is created._
:heart: Thank you for your contribution!
=> test(args): add missing `embed` feature guard

src/args.rs, src/describe/mod.rs, src/describe/stub.rs
Fixes: #373
BREAKING CHANGE: New field `variadic` added to `Parameter` struct.
Added basic stubs for rust closure. This will always be included if the `closure` feature is enabled.
No argument information, as that is not rly available, but better than having no stubs.
_Check the boxes that apply (put an `x` in the brackets, like `[x]`). You can also check boxes after the PR is created._
:heart: Thank you for your contribution!
=> feat(stubs)!: add stubs for `RustClosure`

crates/macros/src/function.rs, crates/macros/src/impl_.rs, crates/macros/src/lib.rs, crates/macros/src/parsing.rs, guide/src/macros/impl.md, src/builders/class.rs, src/class.rs, tests/src/integration/class/class.php, tests/src/integration/class/mod.rs
Add visability in constructor meta, and feature mark constructor as private and protected
- Add MethodFlags to ConstructorMeta 
- Relevant or closing issues[ (https://github.com/davidcole1340/ext-php-rs/issues/541)
- I made fast solution, and it could be not neat
_Check the boxes that apply (put an `x` in the brackets, like `[x]`). You can also check boxes after the PR is created._
:heart: Thank you for your contribution!
=> feat: Add constructor visability
